### ISSUE TITLE
[Fabric 1.21.1] v5.0.8 is incorrectly labeled as (in)compatible with 1.21

### ISSUE THREAD

**Issue by RMEngelbrecht** [dimadencep/RemoveReloadingScreen#113]
### Minecraft version.

1.21

### Remove Reloading Screen version.

v5.0.8

### What happened?

v5.0.8 is incorrectly labelled as (in)compatible with Minecraft v1.21.

The mod is listed as compatible with 1.21 and 1.21.1 on Modrinth and CurseForge, but is set to be incompatible with 1.21 in gradle.
I can imagine the mod is compatible with 1.21 due to how little difference there is, but that one of these is incorrect is certain.

### Relevant log.

[21:42:43] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.16.5
[21:42:43] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[21:42:43] [main/WARN]: Mod resolution failed
[21:42:43] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED rrls 5.0.8+mc1.21.1-fabric {depends minecraft @ [>=1.21.1]}, ROOT_FORCELOAD_SINGLE rrls 5.0.8+mc1.21.1-fabric]
[21:42:43] [main/INFO]: Reason: [HARD_DEP rrls 5.0.8+mc1.21.1-fabric {depends minecraft @ [>=1.21.1]}]
[21:42:43] [main/INFO]: Fix: add [], remove [], replace [[minecraft 1.21] -> add:minecraft 1.21.1 ([[1.21.1,∞)])]
[21:42:43] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.21 with version 1.21.1 or later.
More details:
	 - Mod 'Remove Reloading Screen' (rrls) 5.0.8+mc1.21.1-fabric requires version 1.21.1 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]

**Comment by Franco227** [comment]
Can confirm

**Comment by dima-dencep** [comment]
Why don't you just update to 1.21.1?
I was sleepy when I did it and forgot that it doesn't need to be done

**Comment by RMEngelbrecht** [comment]
Because of other mod compatibility. Would update otherwise but I'm bottlenecked by other mods 🤷‍♂️
