### ISSUE TITLE
Version 5.0.8 reports as not for 1.21.1 in fabric

### ISSUE THREAD

**Issue by lerokko** [dimadencep/RemoveReloadingScreen#114]
### Minecraft version.

1.21.1

### Remove Reloading Screen version.

5.0.8

### What happened?

Crashes as it says it is only for 1.21 but the wrong version 1.21.1 is present

### Relevant log.

```
[12:53:17] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.16.5
[12:53:18] [ForkJoinPool-1-worker-3/WARN]: Mod dev_isxander_libsdl4j uses the version 3.6896c4c-38 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '6896c4c'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:53:18] [ForkJoinPool-1-worker-4/WARN]: Mod org_cloudburstmc_netty_netty-transport-raknet uses the version 1.0.0.CR3-SNAPSHOT which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'CR3'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:53:18] [main/WARN]: Mod resolution failed
[12:53:18] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED rrls 5.0.8+mc1.21.1-fabric {depends minecraft @ [>=1.21.1]}, ROOT_FORCELOAD_SINGLE rrls 5.0.8+mc1.21.1-fabric]
[12:53:18] [main/INFO]: Reason: [HARD_DEP rrls 5.0.8+mc1.21.1-fabric {depends minecraft @ [>=1.21.1]}]
[12:53:18] [main/INFO]: Fix: add [], remove [], replace [[rrls 5.0.8+mc1.21.1-fabric] -> add:rrls 1 ([(-∞,∞)])]
[12:53:18] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Remove Reloading Screen' (rrls) 5.0.8+mc1.21.1-fabric with any version that is compatible with:
		 - minecraft 1.21
More details:
	 - Mod 'Remove Reloading Screen' (rrls) 5.0.8+mc1.21.1-fabric requires version 1.21.1 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.5.jar:?]
```

**Comment by lerokko** [comment]
The mod is build with {depends minecraft @ [>=1.21.1]} but named or listed incorrectly on curseforge.
It is tagged as a 1.21.1 on the platform and also has 1.21.1 in the name of the file. They do not match. Either the mod dependencies or the curseforge upload are flagged incorrectly. As opposed to 5.07 which is also tagged for 1.21.1 and loads in 1.21.1 as expected.

If this is invalid I would ask you to please at least tell me what is wrong about it. Cause from my side it does not look like I made any mistakes.
